# Generated by Django 5.0.6 on 2024-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='income_types/'),
        ),
    ]
