# Generated by Django 5.0.6 on 2024-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_income_manual_income_image_alter_income_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='wallet_type',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzbekistani Som'), ('USD', 'US Dollar'), ('RUB', 'Russian Rouble')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('crypto', 'Crypto')], default='cash', max_length=6),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Uzbekistani Som'), ('USD', 'US Dollar'), ('RUB', 'Russian Rouble')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('crypto', 'Crypto')], default='cash', max_length=6),
        ),
    ]
