# Generated by Django 5.0.6 on 2024-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_accountbalance_wallet_type_expense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='default_type', max_length=100),
            preserve_default=False,
        ),
    ]
