# Generated by Django 5.0.6 on 2024-07-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
    ]
